version: "3.4"
services:
  client:
    image: client:${ENV}
    build:
      context: client
      dockerfile: Dockerfile.${ENV}
    ports:
      - "1234:1234"
      - "1235:1235"
    depends_on:
      - server
    volumes:
      - ./client:/home/node/code
      - /home/node/code/node_modules
  server:
    image: server:${ENV}
    build:
      context: server
      dockerfile: Dockerfile.${ENV}
    ports:
      - "4000:4000"
    depends_on:
      - auth
      - football
    volumes:
      - ./server:/home/node/code
      - /home/node/code/node_modules
  auth:
    image: auth:${ENV}
    build:
      context: auth
      dockerfile: Dockerfile.${ENV}
    volumes:
      - ./auth:/project
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
  football:
    image: football:${ENV}
    build:
      context: football
      dockerfile: Dockerfile.${ENV}
    volumes:
      - ./football:/project
    depends_on:
      - db
    ports:
      - "3003:3003"
    environment:
      - DATABASE_URL=${DATABASE_URL}
  sidekiq:
    image: sidekiq:${ENV}
    build:
      context: football
      dockerfile: Dockerfile.${ENV}
    command: bundle exec sidekiq
    volumes:
      - ./football:/project
      - /project/tmp
    depends_on:
      - db
      - redis
      - crawler
    environment:
      - REDIS_URL_SIDEKIQ=${REDIS_URL}
      - DATABASE_URL=${DATABASE_URL}
  crawler:
    image: crawler:${ENV}
    build:
      context: crawler
      dockerfile: Dockerfile.${ENV}
    volumes:
      - ./crawler:/project
    ports:
      - "5000:5000"
  db:
    image: postgres:15
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
  redis:
    image: redis:7.2.1-alpine
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis:/data

volumes:
  postgres:
  redis:
