apiVersion: v1
kind: Service
metadata:
  labels:
    app: crawler
  name: crawler
spec:
  type: NodePort
  ports:
  - name: "5000"
    port: 5000
    targetPort: 5000
    nodePort: 31241
  selector:
    app: crawler
