apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: football
  name: football
spec:
  replicas: 1
  selector:
    matchLabels:
      app: football
  template:
    metadata:
      labels:
        app: football
    spec:
      containers:
        - image: football:dev
          name: football
          ports:
            - containerPort: 3003
