apiVersion: v1
data:
  nginx.conf: |-
    server {
        listen 80;

        location / {
            proxy_pass http://127.0.0.1:1234;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
        }

        location /graphql {
            proxy_pass http://server:4000;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
        }

        location /subscriptions {
            proxy_pass http://server:4000/subscriptions;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
        }

        location ~^/sidekiq {
            proxy_pass http://football:3003;
        }
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: nginx-config
