apiVersion: v1
kind: Service
metadata:
  name: server
spec:
  type: NodePort
  ports:
    - name: "4000"
      port: 4000
      targetPort: 4000
      nodePort: 31236
  selector:
    app: server
status:
  loadBalancer: {}
